apiVersion: ocs.openshift.io/v1

kind: StorageCluster

metadata:

  name: ocs-storagecluster

  namespace: openshift-storage

spec:

  labelSelector:

    matchExpressions: []

  monDataDirHostPath: /var/lib/rook

  storageDeviceSets:

  - count: 1

    dataPVCTemplate:

      spec:

        accessModes:

        - ReadWriteOnce

        resources:

          requests:

            storage: 30Gi

        storageClassName: 'localblock-sc' 

        volumeMode: Block

    name: ocs-deviceset

    placement: {}

    portable: true

    replica: 3

